export const GALLERY_FETCH_GALLERY_BEGIN = 'GALLERY_FETCH_GALLERY_BEGIN';
export const GALLERY_FETCH_GALLERY_SUCCESS = 'GALLERY_FETCH_GALLERY_SUCCESS';
export const GALLERY_FETCH_GALLERY_FAILURE = 'GALLERY_FETCH_GALLERY_FAILURE';
