export const STORE_FETCH_PRODUCT_BEGIN = 'STORE_FETCH_PRODUCT_BEGIN';
export const STORE_FETCH_PRODUCT_SUCCESS = 'STORE_FETCH_PRODUCT_SUCCESS';
export const STORE_FETCH_PRODUCT_FAILURE = 'STORE_FETCH_PRODUCT_FAILURE';
