export const ADMIN_NAVOPEN = 'ADMIN_NAVOPEN';
export const ADMIN_CATEGORY_IMAGE = 'ADMIN_CATEGORY_IMAGE';
export const ADMIN_CATEGORY_ADD = 'ADMIN_CATEGORY_ADD';

export const ADMIN_CATEGORY_ADD_IMAGE_BEGIN = 'ADMIN_CATEGORY_ADD_IMAGE_BEGIN';
export const ADMIN_CATEGORY_ADD_IMAGE_SUCCESS = 'ADMIN_CATEGORY_ADD_IMAGE_SUCCESS';
export const ADMIN_CATEGORY_ADD_IMAGE_FAILUR = 'ADMIN_CATEGORY_ADD_IMAGE_FAILUR';


export const ADMIN_EDIT_CATEGORY = 'ADMIN_EDIT_CATEGORY';
export const ADMIN_EDIT_CATEGORY_BEGIN = 'ADMIN_EDIT_CATEGORY_BEGIN';
export const ADMIN_EDIT_CATEGORY_SUCCESS = 'ADMIN_EDIT_CATEGORY_SUCCESS';
export const ADMIN_EDIT_CATEGORY_FAILURE = 'ADMIN_EDIT_CATEGORY_FAILURE';


export const ADMIN_CATEGORY_ADD_BEGIN = 'ADMIN_CATEGORY_ADD_BEGIN';
export const ADMIN_CATEGORY_ADD_SUCCESS = 'ADMIN_CATEGORY_ADD_SUCCESS';
export const ADMIN_CATEGORY_ADD_FAILUR = 'ADMIN_CATEGORY_ADD_FAILUR';

export const ADMIN_FETCH_CATEGORY_LIST_BEGIN = 'ADMIN_FETCH_CATEGORY_LIST_BEGIN';
export const ADMIN_FETCH_CATEGORY_LIST_SUCCESS = 'ADMIN_FETCH_CATEGORY_LIST_SUCCESS';
export const ADMIN_FETCH_CATEGORY_LIST_FAILURE = 'ADMIN_FETCH_CATEGORY_LIST_FAILURE';

export const ADMIN_PRODUCT_ADD = 'ADMIN_PRODUCT_ADD';
export const ADMIN_PRODUCT_ADD_BEGIN = 'ADMIN_PRODUCT_ADD_BEGIN';
export const ADMIN_PRODUCT_ADD_SUCCESS = 'ADMIN_PRODUCT_ADD_SUCCESS';
export const ADMIN_PRODUCT_ADD_FAILUR = 'ADMIN_PRODUCT_ADD_FAILUR';


export const ADMIN_PRODUCT_IMAGE = 'ADMIN_PRODUCT_IMAGE';
export const ADMIN_PRODUCT_IMAGE_ADD_BEGIN = 'ADMIN_PRODUCT_IMAGE_ADD_BEGIN';
export const ADMIN_PRODUCT_IMAGE_ADD_SUCCESS = 'ADMIN_PRODUCT_IMAGE_ADD_SUCCESS';
export const ADMIN_PRODUCT_IMAGE_ADD_FAILUR = 'ADMIN_PRODUCT_IMAGE_ADD_FAILUR';


export const ADMIN_FETCH_PRODUCT_LIST = 'ADMIN_FETCH_PRODUCT_LIST';
export const ADMIN_FETCH_PRODUCT_LIST_BEGIN = 'ADMIN_FETCH_PRODUCT_LIST_BEGIN';
export const ADMIN_FETCH_PRODUCT_LIST_SUCCESS = 'ADMIN_FETCH_PRODUCT_LIST_SUCCESS';
export const ADMIN_FETCH_PRODUCT_LIST_FAILURE = 'ADMIN_FETCH_PRODUCT_LIST_FAILURE';







export const ADMIN_DELETE_CATEGORY = 'ADMIN_DELETE_CATEGORY';
export const ADMIN_DELETE_CATEGORY_BEGIN = 'ADMIN_DELETE_CATEGORY_BEGIN';
export const ADMIN_DELETE_CATEGORY_SUCCESS = 'ADMIN_DELETE_CATEGORY_SUCCESS';
export const ADMIN_DELETE_CATEGORY_FAILURE = 'ADMIN_DELETE_CATEGORY_FAILURE';



export const ADMIN_DELETE_PRODUCT = 'ADMIN_DELETE_PRODUCT';
export const ADMIN_DELETE_PRODUCT_BEGIN = 'ADMIN_DELETE_PRODUCT_BEGIN';
export const ADMIN_DELETE_PRODUCT_SUCCESS = 'ADMIN_DELETE_PRODUCT_SUCCESS';
export const ADMIN_DELETE_PRODUCT_FAILURE = 'ADMIN_DELETE_PRODUCT_FAILURE';


export const ADMIN_EDIT_PRODUCT = 'ADMIN_EDIT_PRODUCT';
export const ADMIN_EDIT_PRODUCT_BEGIN = 'ADMIN_EDIT_PRODUCT_BEGIN';
export const ADMIN_EDIT_PRODUCT_SUCCESS = 'ADMIN_EDIT_PRODUCT_SUCCESS';
export const ADMIN_EDIT_PRODUCT_FAILURE = 'ADMIN_EDIT_PRODUCT_FAILURE';

export const ADMIN_IMAGE_UPLOAD_BEGIN = 'ADMIN_IMAGE_UPLOAD_BEGIN';
export const ADMIN_IMAGE_UPLOAD_SUCCESS = 'ADMIN_IMAGE_UPLOAD_SUCCESS';
export const ADMIN_IMAGE_UPLOAD_FAILURE = 'ADMIN_IMAGE_UPLOAD_FAILURE';

export const ADMIN_FETCH_GALLERY_BEGIN = 'ADMIN_FETCH_GALLERY_BEGIN';
export const ADMIN_FETCH_GALLERY_SUCCESS = 'ADMIN_FETCH_GALLERY_SUCCESS';
export const ADMIN_FETCH_GALLERY_FAILURE = 'ADMIN_FETCH_GALLERY_FAILURE';


export const ADMIN_DELETE_GALLERY_IMAGE_BEGIN = 'ADMIN_DELETE_GALLERY_IMAGE_BEGIN';
export const ADMIN_DELETE_GALLERY_IMAGE_SUCCESS = 'ADMIN_DELETE_GALLERY_IMAGE_SUCCESS';
export const ADMIN_DELETE_GALLERY_IMAGE_FAILURE = 'ADMIN_DELETE_GALLERY_IMAGE_FAILURE';


export const ADMIN_NEWS_ADD_BEGIN = 'ADMIN_NEWS_ADD_BEGIN';
export const ADMIN_NEWS_ADD_SUCCESS = 'ADMIN_NEWS_ADD_SUCCESS';
export const ADMIN_NEWS_ADD_FAILURE = 'ADMIN_NEWS_ADD_FAILURE';


export const ADMIN_FETCH_NEWS_BEGIN = 'ADMIN_FETCH_NEWS_BEGIN';
export const ADMIN_FETCH_NEWS_SUCCESS = 'ADMIN_FETCH_NEWS_SUCCESS';
export const ADMIN_FETCH_NEWS_FAILURE = 'ADMIN_FETCH_NEWS_FAILURE';

export const ADMIN_EDIT_NEWS_BEGIN = 'ADMIN_EDIT_NEWS_BEGIN';
export const ADMIN_EDIT_NEWS_SUCCESS = 'ADMIN_EDIT_NEWS_SUCCESS';
export const ADMIN_EDIT_NEWS_FAILURE = 'ADMIN_EDIT_NEWS_FAILURE';

export const ADMIN_DELETE_NEWS_BEGIN = 'ADMIN_DELETE_NEWS_BEGIN';
export const ADMIN_DELETE_NEWS_SUCCESS = 'ADMIN_DELETE_NEWS_SUCCESS';
export const ADMIN_DELETE_NEWS_FAILURE = 'ADMIN_DELETE_NEWS_FAILURE';
