export const NEWS_FETCH_NEWS_WITH_ID_BEGIN = 'NEWS_FETCH_NEWS_WITH_ID_BEGIN';
export const NEWS_FETCH_NEWS_WITH_ID_SUCCESS = 'NEWS_FETCH_NEWS_WITH_ID_SUCCESS';
export const NEWS_FETCH_NEWS_WITH_ID_FAILURE = 'NEWS_FETCH_NEWS_WITH_ID_FAILURE';
